import { create } from 'zustand';
import { BlockType, DysonProgressMetrics } from '../types';
import { UPGRADES, UpgradeId } from '../data/upgrades';

// LCG constants from Numerical Recipes – produce a uniform pseudo-random sequence.
// The seed is masked to 31 bits (& 0x7fffffff), so the sequence cycles after 2^31 jumps.
const LCG_MULTIPLIER = 1664525;
const LCG_INCREMENT = 1013904223;

interface StoreState {
  matter: number;
  rareMatter: number;
  energy: number;
  energyGenerationRate: number;
  droneCount: number;
  droneCost: number;
  prestigeLevel: number;
  /** Persistent meta-currency earned on each System Jump. Never reset. */
  stellarCrystals: number;
  /** Persistent research currency generated by exploring drones. Persists across System Jumps. */
  research: number;
  /** Seed that drives procedural variation for the current star system. Updated on each jump. */
  systemSeed: number;
  selectedTool: 'LASER' | 'BUILD';
  selectedBlueprint: BlockType;
  asteroidOrbitEnabled: boolean;
  asteroidOrbitRadius: number;
  asteroidOrbitSpeed: number;
  asteroidOrbitVerticalAmplitude: number;

  /** Automatically place blueprints over time when enabled */
  autoBlueprintEnabled: boolean;
  /** Runtime mode for Auto-Replicator behavior after upgrade purchase. */
  autoReplicatorEnabled: boolean;
  dysonProgress: DysonProgressMetrics;

  /** Tech tree: record of purchased upgrade IDs */
  upgrades: Record<UpgradeId, boolean>;

  // UI State
  isSettingsOpen: boolean;
  isUpgradesOpen: boolean;
  showDebugPanel: boolean;

  // Actions
  resetWorld: () => void;
  addMatter: (amount: number) => void;
  addRareMatter: (amount: number) => void;
  addEnergy: (amount: number) => void;
  setEnergyRate: (rate: number) => void;
  consumeMatter: (amount: number) => boolean;
  consumeRareMatter: (amount: number) => boolean;
  addDrone: () => void;
  addResearch: (amount: number) => void;
  setTool: (tool: 'LASER' | 'BUILD') => void;
  setBlueprint: (type: BlockType) => void;
  setAsteroidOrbitEnabled: (enabled: boolean) => void;
  setAsteroidOrbitRadius: (radius: number) => void;
  setAsteroidOrbitSpeed: (speed: number) => void;
  setAsteroidOrbitVerticalAmplitude: (amplitude: number) => void;

  // auto-blueprint actions
  setAutoBlueprintEnabled: (enabled: boolean) => void;
  toggleAutoBlueprint: () => void;
  setAutoReplicatorEnabled: (enabled: boolean) => void;
  toggleAutoReplicator: () => void;
  setDysonProgress: (progress: DysonProgressMetrics) => void;

  // Upgrade actions
  purchaseUpgrade: (id: UpgradeId) => boolean;

  // UI Actions
  toggleSettings: () => void;
  toggleUpgrades: () => void;
  toggleDebugPanel: () => void;
}

export const useStore = create<StoreState>((set, get) => ({
  matter: 0,
  rareMatter: 0,
  energy: 100,
  energyGenerationRate: 0,
  droneCount: 0,
  droneCost: 50,
  prestigeLevel: 0,
  stellarCrystals: 0,
  research: 0,
  systemSeed: 0,
  selectedTool: 'LASER',
  selectedBlueprint: BlockType.FRAME,
  asteroidOrbitEnabled: false,
  asteroidOrbitRadius: 24,
  asteroidOrbitSpeed: 0.08,
  asteroidOrbitVerticalAmplitude: 2,
  autoBlueprintEnabled: false,
  autoReplicatorEnabled: false,
  dysonProgress: {
    blueprintFrames: 0,
    frames: 0,
    panels: 0,
    shells: 0,
    milestones: 0,
    prestigeReady: false,
  },
  upgrades: {
    MINING_SPEED_1: false,
    DRONE_SPEED_1: false,
    LASER_EFFICIENCY_1: false,
    AUTO_REPLICATOR: false,
    DEEP_SCAN_1: false,
    ADVANCED_EXPLORER: false,
  },
  isSettingsOpen: false,
  isUpgradesOpen: false,
  showDebugPanel: false,

  // auto-blueprint methods
  setAutoBlueprintEnabled: (enabled) => set({ autoBlueprintEnabled: enabled }),
  toggleAutoBlueprint: () => set((state) => ({ autoBlueprintEnabled: !state.autoBlueprintEnabled })),
  setAutoReplicatorEnabled: (enabled) =>
    set((state) => (state.upgrades.AUTO_REPLICATOR ? { autoReplicatorEnabled: enabled } : {})),
  toggleAutoReplicator: () =>
    set((state) =>
      state.upgrades.AUTO_REPLICATOR
        ? { autoReplicatorEnabled: !state.autoReplicatorEnabled }
        : {}
    ),
  setDysonProgress: (progress) => set({ dysonProgress: progress }),

  toggleSettings: () => set((state) => ({ isSettingsOpen: !state.isSettingsOpen })),
  toggleUpgrades: () => set((state) => ({ isUpgradesOpen: !state.isUpgradesOpen })),
  toggleDebugPanel: () => set((state) => ({ showDebugPanel: !state.showDebugPanel })),

  purchaseUpgrade: (id) => {
    const state = get();
    if (state.upgrades[id]) return false; // already purchased
    const def = UPGRADES.find((u) => u.id === id);
    if (!def) return false;
    if (
      state.matter < def.matterCost ||
      state.rareMatter < def.rareMatterCost ||
      state.research < def.researchCost
    )
      return false;
    set((s) => ({
      matter: s.matter - def.matterCost,
      rareMatter: s.rareMatter - def.rareMatterCost,
      research: s.research - def.researchCost,
      autoReplicatorEnabled:
        id === 'AUTO_REPLICATOR' ? true : s.autoReplicatorEnabled,
      upgrades: { ...s.upgrades, [id]: true },
    }));
    return true;
  },

  addMatter: (amount) => set((state) => ({ matter: state.matter + amount })),
  addRareMatter: (amount) => set((state) => ({ rareMatter: state.rareMatter + amount })),
  addEnergy: (amount) => set((state) => ({ energy: state.energy + amount })),
  setEnergyRate: (rate) => set({ energyGenerationRate: rate }),
  addResearch: (amount) => set((state) => ({ research: state.research + amount })),
  
  resetWorld: () => set((state) => {
    // ── PRESTIGE ECONOMY ──────────────────────────────────────────────────────
    // Crystals earned this run: rare-matter haul + per-prestige bonus.
    const crystalsEarned = Math.floor(state.rareMatter / 2) + state.prestigeLevel * 5;
    // Next seed via LCG – gives deterministic per-system variation.
    const nextSeed = ((state.systemSeed * LCG_MULTIPLIER + LCG_INCREMENT) & 0x7fffffff);
    return {
      // ── RESET (per-system state) ───────────────────────────────────────────
      matter: 0,
      rareMatter: 0,
      energy: 0,
      energyGenerationRate: 0,
      droneCount: 0,
      droneCost: 50,
      autoReplicatorEnabled: false,
      dysonProgress: {
        blueprintFrames: 0,
        frames: 0,
        panels: 0,
        shells: 0,
        milestones: 0,
        prestigeReady: false,
      },
      upgrades: {
        MINING_SPEED_1: false,
        DRONE_SPEED_1: false,
        LASER_EFFICIENCY_1: false,
        AUTO_REPLICATOR: false,
        DEEP_SCAN_1: false,
        ADVANCED_EXPLORER: false,
      },
      // ── KEEP (persistent across jumps) ────────────────────────────────────
      prestigeLevel: state.prestigeLevel + 1,
      stellarCrystals: state.stellarCrystals + crystalsEarned,
      systemSeed: nextSeed,
    };
  }),

  consumeMatter: (amount) => {
    const { matter } = get();
    if (matter >= amount) {
      set({ matter: matter - amount });
      return true;
    }
    return false;
  },

  consumeRareMatter: (amount) => {
    const { rareMatter } = get();
    if (rareMatter >= amount) {
      set({ rareMatter: rareMatter - amount });
      return true;
    }
    return false;
  },

  addDrone: () => {
    const { matter, droneCost, droneCount } = get();
    if (matter >= droneCost) {
      set({
        matter: matter - droneCost,
        droneCount: droneCount + 1,
        droneCost: Math.floor(droneCost * 1.2),
      });
    }
  },

  setTool: (tool) => set({ selectedTool: tool }),
  setBlueprint: (type) => set({ selectedBlueprint: type }),
  setAsteroidOrbitEnabled: (enabled) => set({ asteroidOrbitEnabled: enabled }),
  setAsteroidOrbitRadius: (radius) => set({ asteroidOrbitRadius: Math.max(0, radius) }),
  setAsteroidOrbitSpeed: (speed) => set({ asteroidOrbitSpeed: speed }),
  setAsteroidOrbitVerticalAmplitude: (amplitude) =>
    set({ asteroidOrbitVerticalAmplitude: Math.max(0, amplitude) }),
}));
